repos:
-   hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
-   hooks:
    -   id: uv-lock
    repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.22
-   hooks:
    -   id: absolufy-imports
    repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
-   hooks:
    -   args:
        -   --fix
        id: ruff
    -   id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
-   hooks:
    -   id: pyright
    repo: https://github.com/RobertCraigie/pyright-python
    # 1.1.395 has a bug that complains about defaults
    rev: v1.1.405
-   hooks:
    -   id: markdownlint
    repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0